### ISSUE TITLE
constrain() returns zero-dimensional array instead of float

### ISSUE THREAD

**Issue by smlpt** [py5coding/py5generator#319] opened 2023-07-17 09:14 UTC
So I wanted to use constrain() to limit the possible mouse speed that is passed to a 2D vector. However, I always get the error saying that the object is not iterable. Minimal example:

```python
maxvel = 3 
velx = constrain(mouse_x-pmouse_x, -maxvel, maxvel)
vely = constrain(mouse_y-pmouse_y, -maxvel, maxvel)
vel = Py5Vector2D(velx, vely)
```

The error seems to come from the fact that constrain() returns an NDArray instead of just an int or float (see [this line](https://github.com/py5coding/py5generator/blob/bbe1c48a7ca02e5f5331eb3734fad4ee35c86d83/py5_resources/py5_module/py5/mixins/math.py#L108C4-L108C4)). It seems to work in [your example](https://py5coding.org/reference/sketch_constrain.html), but it doesn't work in my case. I'm not sure if this is a bug or if this is expected behavior. I can circumvent it by calling `velx.item()` instead.

**Comment by hx2A** [comment] 2023-07-17 12:28
@smlpt , thank you for the bug report. I looked at the Py5Vector constructor and I see what the problem is. There's a place where it is checking that the argument is a numpy array but it should also check the numpy array's shape. Right now it is assuming the dimensionality is 1. It also needs to handle dimensions of 0 and >= 2.

I intend to do a release this week and will get this fix in.

Your workaround is effective. I can also suggest trying something like this:

```python
vel = Py5Vector2D(constrain(np.array([mouse_x - pmouse_x, mouse_y - pmouse_y]), -maxvel, maxvel))
```

Similar to your example, this constrains each of the x and y velocities to 3, which is like constraining the velocity to a square. The diagonal velocity can be 3 * 1.414.

Depending on your use case, you might like this:

```python
vel = Py5Vector2D(mouse_x - pmouse_x, mouse_y - pmouse_y).set_limit(3)
```

That limits the vector's magnitude to 3, constraining the velocity to 3 for any direction, including the diagonals.

**Comment by smlpt** [comment] 2023-07-17 12:46
Good to see you could reproduce it.

Yours is of course a way more elegant solution, thank you very much! And thank you also for developing this awesome piece of software, it's much appreciated.

**Comment by hx2A** [comment] 2023-07-17 17:18
I just merged a PR to fix this.

While investigating the problem you found, I also discovered that these don't work correctly either:

```python
Py5Vector(np.arange(4).reshape(2, 2))
Py5Vector(np.arange(2).reshape(2, 1, 1), np.array(2), np.array([3]))
```

I fixed this also.

> And thank you also for developing this awesome piece of software, it's much appreciated.

You are welcome! And thank you for contributing to making py5 even better!

**Closed by hx2A** 2023-07-17 17:18 UTC
